CC=javac

all:
	$(CC) dllp/Server.java
	$(CC) dllp/ClientClass.java
	$(CC) dllp/SAWReceiverClientClass.java
	$(CC) dllp/SAWSenderClientClass.java
	$(CC) dllp/Client.java
	$(CC) dllp/SAWReceiverClient.java
	$(CC) dllp/SAWSenderClient.java

clean:
	rm -rf ./*.class
	rm -rf ./*/*.class
