CC=javac

all:
	$(CC) dllp/Server.java
	$(CC) dllp/ClientClass.java
	$(CC) dllp/SAWReceiverClientClass.java
	$(CC) dllp/SAWSenderClientClass.java
	$(CC) dllp/SAWReceiverClient.java
	$(CC) dllp/SAWSenderClient.java
	$(CC) dllp/GNReceiverClientClass.java
	$(CC) dllp/GNSenderClientClass.java -Xlint
	$(CC) dllp/GNReceiverClient.java
	$(CC) dllp/GNSenderClient.java
	$(CC) dllp/SRReceiverClientClass.java
	$(CC) dllp/SRSenderClientClass.java -Xlint
	$(CC) dllp/SRReceiverClient.java
	$(CC) dllp/SRSenderClient.java
	$(CC) dllp/Client.java

clean:
	rm -rf ./*.class
	rm -rf ./*/*.class
