######################################################################
# Automatically generated by qmake (3.0) Tue Oct 1 02:32:50 2019
######################################################################

TEMPLATE = app
TARGET = Display_simulator
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += sources/algo.h sources/contolpanel.h sources/graph.h
SOURCES += Display_simulator.cpp
