######################################################################
# Automatically generated by qmake (3.0) Fri Aug 9 23:56:41 2019
######################################################################

TEMPLATE = app
TARGET = Display_simulator
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += sources/graph.h
SOURCES += Display_simulator.cpp
