CREATE TABLE EMP(
	EMP_CODE CHAR(5) PRIMARY KEY, 
	EMP_NAME CHAR(20), 
	DEPT_CODE CHAR(5), 
	DESIG_CODE CHAR(5), 
	SEX CHAR(1), 
	ADDRESS CHAR(25), 
	CITY CHAR(20), 
	STATE CHAR(20), 
	PIN CHAR(6), 
	BASIC NUMERIC, 
	JN_DT DATE
);

CREATE TABLE DESIGNATION(
	DESIG_CODE CHAR(5) PRIMARY KEY,
	DESIG_DESC CHAR(20)
);

CREATE TABLE DEPARTMENT(
	DEPT_CODE CHAR(5) PRIMARY KEY,
	DEPT_NAME CHAR(15)
);

DESC EMP;
DESC DESIGNATION;
DESC DEPARTMENT;

INSERT INTO DESIGNATION VALUES('MGR','Manager');
INSERT INTO DESIGNATION VALUES('EXEC','Executive');
INSERT INTO DESIGNATION VALUES('OFR','Officer');
INSERT INTO DESIGNATION VALUES('CLK','Clerk');
INSERT INTO DESIGNATION VALUES('HLPR','Helper');

INSERT INTO DEPARTMENT VALUES('PER','Personnel');
INSERT INTO DEPARTMENT VALUES('PROD','Production');
INSERT INTO DEPARTMENT VALUES('PRCH','Purchase');
INSERT INTO DEPARTMENT VALUES('FNC','Finance');
INSERT INTO DEPARTMENT VALUES('RSH','Research');

INSERT INTO EMP VALUES('00000', 'SAHIL', 'RSH', 'MGR', 'M', 'Islampur', 'Dubrajpur', 'WB', '731123', 100000, '2017-07-01');
INSERT INTO EMP VALUES('00001', 'BIKRAM', 'RSH', 'EXEC', 'M', 'Benachiti', 'Durgapur', 'WB', '770433', 50000, '2017-07-01');
